### ISSUE TITLE
destructivelyDeleteFromObjectByKey function

### ISSUE THREAD

**Issue by gasganno** [learn-co-curriculum/javascript-objects-lab#20]
I don't understand why this doesn't work as a solution:

function destructivelyDeleteFromObjectByKey(object, key) {
  delete object.key
  return object
}

but this does:

function destructivelyDeleteFromObjectByKey(object, key) {
  delete object[key]
  return object
}

In the Javascript Objects lesson there is one method given for deleting a key-value pair:
![screen shot 2017-09-22 at 5 59 27 pm](https://user-images.githubusercontent.com/26098882/30765930-0e59d574-9fc0-11e7-9cb5-627fedcca707.png)

There isn't anything about using brackets. If the dot notation won't work in a simple function like this, where does it work?

**Comment by djsabox** [comment]
dot notation only works when you have an exact/defined key.
you can't use dot notation with variables. you need the [] to execute a variable command.

for example: 

var key = "example" 
var object = {key: "1", example: "2"}

using . notation, (object.key) will return "1"
Using [] notation (object[key]) will return "2"

**Comment by drakeltheryuujin** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab.

The issue here appears to be with your own code. If the error messages in the test suite are not providing enough information for you to diagnose the problem, try the following three things:
1. Run your code as it is intended to be run. That is, don't simply rely on the test suite to check the functionality of your code — check it yourself! For Ruby code, add some lines to the bottom of the file that call your methods and output verifiable information to the terminal. For Sinatra or Rails applications, fire up your local server and try executing the same actions that the test suite is failing to complete. For JavaScript code, open up your browser's JS console, paste in your code, and play around with your functions and variables.
2. Use [Pry](https://www.sitepoint.com/rubyists-time-pry-irb/) to poke around your [Ruby](https://github.com/pry/pry) (or Sinatra), [Rails](https://github.com/rweng/pry-rails), or [JavaScript](https://github.com/blainesch/pry.js) code step-by-step. Check that the values of particular variables are what you expect them to be at various points throughout the program's execution.
3. Use the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after reviewing your code and consulting AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙

**Comment by gasganno** [comment]
Hi,
I'm not sure why this is suddenly getting attention after a year but my comment _was_ related to what the curriculum did and did not explain. 

The lesson gave one method for deleting a key-value pair and it didn't work in the context of the lab.

Yes, my code was initially incorrect, but only because I followed the method given in the lesson. When the lesson teaches 'Do x to achieve y' and the method doesn't work that seems like an issue with the lesson not giving enough information.

Thanks, Jarrod
