### ISSUE TITLE
Submit Pull Request not available after completing tests

### ISSUE THREAD

**Issue by BaronLip** [learn-co-curriculum/javascript-objects-lab#25]
I'm unable to click on submit after using "learn submit" within the terminal. Thus, preventing me from continuing without skipping under the curriculum pull down on the left. 

Thanks.

![Submit Pull Request issue2](https://user-images.githubusercontent.com/45054120/56941247-ee007b80-6ad8-11e9-9871-9f0738f0fafb.png)

**Comment by maxwellbenton** [comment]
Hi @BaronLip,

Sorry to hear that you were experiencing problems with Learn. This issue is due to a bug in Learn, and our engineering team has been notified. If you continue to experience this issue on future lessons, please feel free to reach out to support@learn.co for further assistance.

Thank you!
